# Generated by Django 3.2.10 on 2022-04-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('image_name', models.CharField(blank=True, max_length=70, null=True)),
                ('annotation_index', models.IntegerField(blank=True, null=True)),
                ('view_group', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Project View',
                'verbose_name_plural': 'Project Views',
            },
        ),
        migrations.CreateModel(
            name='InventoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default='Full View', max_length=500, null=True)),
                ('instance_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sketchfab Group ID')),
                ('project_views', models.ManyToManyField(to='backend.Image', verbose_name='Project Views')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='ProjectInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('group', models.BooleanField(blank=True, default=False, null=True)),
                ('group_name', models.ManyToManyField(to='backend.InventoryGroup', verbose_name='inventory-Group')),
            ],
            options={
                'verbose_name': 'Project Inventory',
                'verbose_name_plural': 'Project Inventories',
            },
        ),
        migrations.CreateModel(
            name='SketchfabData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=500)),
                ('project_title', models.CharField(max_length=500, verbose_name='Project Name')),
                ('project_logo', models.ImageField(upload_to='media', verbose_name='Project Logo')),
                ('project_image', models.ImageField(upload_to='media', verbose_name='Project Image')),
                ('project_inventory', models.ManyToManyField(to='backend.ProjectInventory', verbose_name='inventory')),
            ],
            options={
                'verbose_name': '3D Floorplan',
                'verbose_name_plural': '3D Floorplans',
            },
        ),
    ]
